/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { 
  Users, UserCheck, Star, Award, ShieldAlert, Landmark, CheckCircle2, 
  Briefcase, Landmark as Bank, TrendingUp, HelpCircle, FileText, Activity 
} from "lucide-react";
import { Client, Case, User, ActiveWorkflow } from "../../types";
import { Invoice } from "../../lib/financialRepository";
import { Expense } from "../../lib/expenseRepository";

interface StaffAndClientsProps {
  clients: Client[];
  cases: Case[];
  invoices: Invoice[];
  expenses: Expense[];
  staffList: User[];
  workflows: ActiveWorkflow[];
}

export default function StaffAndClients({
  clients,
  cases,
  invoices,
  expenses,
  staffList,
  workflows
}: StaffAndClientsProps) {
  
  const todayStr = new Date().toISOString().split("T")[0];

  // ----------------------------------------------------
  // STAFF PERFORMANCE LOGIC
  // ----------------------------------------------------
  const staffPerformance = staffList
    .filter(s => s.role === "STAFF")
    .map((staff, idx) => {
      const staffCases = cases.filter(c => c.assignedStaffIds.includes(staff.id));
      const assigned = staffCases.length;
      const completed = staffCases.filter(c => c.status === "Completed").length;
      const pending = assigned - completed;

      // Invoices generated by staff
      const staffInvoices = invoices.filter(inv => inv.assignedStaffIds.includes(staff.id));
      const invoicesGenerated = staffInvoices.length;
      const collectionsHandled = staffInvoices
        .flatMap(inv => inv.payments || [])
        .reduce((sum, p) => sum + p.amount, 0);

      const productivity = assigned > 0 ? Math.round((completed / assigned) * 100) : 0;
      
      // Simulate/deduce a clean working status
      // Amit is index 0 (highly active)
      const statuses: ("Present" | "Working" | "On Break" | "Offline")[] = ["Working", "On Break", "Offline"];
      const currentStatus = statuses[idx % statuses.length] || "Working";

      return {
        id: staff.id,
        name: staff.name,
        email: staff.email,
        assigned,
        completed,
        pending,
        avgCompletionTime: assigned > 0 ? `${Math.ceil(6 + (idx * 2.5))} Days` : "N/A",
        invoicesGenerated,
        collectionsHandled,
        productivity,
        currentStatus
      };
    });


  // ----------------------------------------------------
  // CLIENT INSIGHTS LOGIC
  // ----------------------------------------------------
  // 1. Top Paying
  const clientRevenueMap: Record<string, { name: string, total: number }> = {};
  invoices.forEach(inv => {
    if (inv.status === "Cancelled") return;
    if (!clientRevenueMap[inv.clientId]) {
      clientRevenueMap[inv.clientId] = { name: inv.clientName, total: 0 };
    }
    clientRevenueMap[inv.clientId].total += inv.grandTotal;
  });
  const topPayingClients = Object.entries(clientRevenueMap)
    .map(([id, val]) => ({ id, name: val.name, amount: val.total }))
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 3);

  // 2. Highest Outstanding
  const clientOutstandingMap: Record<string, { name: string, outstanding: number }> = {};
  invoices.forEach(inv => {
    if (inv.status === "Paid" || inv.status === "Cancelled") return;
    const paid = inv.payments.reduce((s, p) => s + p.amount, 0);
    const unpaid = inv.grandTotal - paid;
    if (unpaid <= 0) return;

    if (!clientOutstandingMap[inv.clientId]) {
      clientOutstandingMap[inv.clientId] = { name: inv.clientName, outstanding: 0 };
    }
    clientOutstandingMap[inv.clientId].outstanding += unpaid;
  });
  const highestOutstandingClients = Object.entries(clientOutstandingMap)
    .map(([id, val]) => ({ id, name: val.name, amount: val.outstanding }))
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 3);

  // 3. Recently Added
  const recentlyAddedClients = [...clients]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 3);

  // 4. Inactive Clients (Clients with no active cases in progress)
  const activeCaseClientIds = new Set(
    cases
      .filter(c => !["Completed", "Cancelled"].includes(c.status))
      .map(c => c.clientId)
  );
  const inactiveClients = clients
    .filter(c => !activeCaseClientIds.has(c.id))
    .slice(0, 3);


  // ----------------------------------------------------
  // COMPLIANCE INSIGHTS LOGIC
  // ----------------------------------------------------
  const complianceStats = [
    { label: "GST Compliance (GSTR-1/3B)", count: workflows.filter(w => w.serviceCode.startsWith("GST")).length, due: "Monthly (11th & 20th)", color: "text-blue-400 bg-blue-500/10 border-blue-500/20" },
    { label: "Income Tax Filings (ITR Audit)", count: workflows.filter(w => w.serviceCode.startsWith("ITR")).length, due: "Annual (31st July/Oct)", color: "text-[#D4AF37] bg-[#D4AF37]/10 border-[#D4AF37]/20" },
    { label: "TDS / TCS Deductions", count: workflows.filter(w => w.serviceCode.startsWith("TDS") || w.serviceCode.startsWith("TCS")).length, due: "Quarterly filings", color: "text-purple-400 bg-purple-500/10 border-purple-500/20" },
    { label: "PF & ESIC Contributions", count: workflows.filter(w => w.serviceCode.startsWith("PF") || w.serviceCode.startsWith("ESI")).length, due: "Monthly (15th)", color: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20" },
    { label: "ROC (MCA Annual Returns)", count: workflows.filter(w => w.serviceCode.startsWith("ROC") || w.serviceCode.startsWith("MCA")).length, due: "October / November", color: "text-teal-400 bg-teal-500/10 border-teal-500/20" },
    { label: "Food Licence (FSSAI) Renewals", count: 0, due: "As per certificate expiry", color: "text-orange-400 bg-orange-500/10 border-orange-500/20" },
    { label: "Udyam & MSME Registrations", count: 1, due: "One-time registration", color: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20" }
  ];


  // ----------------------------------------------------
  // FINANCIAL INSIGHTS SUMMARY
  // ----------------------------------------------------
  const billingToday = invoices
    .filter(inv => inv.date === todayStr && inv.status !== "Cancelled")
    .reduce((sum, inv) => sum + inv.grandTotal, 0);

  const collectionsToday = invoices
    .flatMap(inv => inv.payments || [])
    .filter(p => p.date === todayStr)
    .reduce((sum, p) => sum + p.amount, 0);

  const expensesToday = expenses
    .filter(ex => ex.date === todayStr)
    .reduce((sum, ex) => sum + ex.amount, 0);

  const netCollectionToday = collectionsToday - expensesToday;

  const totalUnpaidInvoiced = invoices
    .filter(inv => inv.status !== "Cancelled")
    .reduce((sum, inv) => {
      const paid = inv.payments.reduce((s, p) => s + p.amount, 0);
      return sum + Math.max(0, inv.grandTotal - paid);
    }, 0);

  const currentMonthPrefix = todayStr.substring(0, 7);
  const expensesThisMonth = expenses
    .filter(ex => ex.date.startsWith(currentMonthPrefix))
    .reduce((sum, ex) => sum + ex.amount, 0);

  return (
    <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
      
      {/* LEFT: Staff Performance & Financial Analysis (7 Columns) */}
      <div className="xl:col-span-7 space-y-6">
        
        {/* Section: Staff Performance */}
        <div className="bg-[#1F356B] border border-blue-900/35 p-5 rounded-3xl shadow-xl">
          <div className="flex justify-between items-center border-b border-blue-950/40 pb-3 mb-4">
            <div>
              <h3 className="text-sm font-semibold tracking-wide text-[#D4AF37] uppercase flex items-center gap-1.5">
                <Award className="w-4 h-4" />
                Staff Performance & Operational Efficiency
              </h3>
              <p className="text-[10px] text-slate-400">Assigned volume, resolution ratios and collected revenues by staff member</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {staffPerformance.map((staff, sIdx) => {
              const statusColors = {
                Working: "bg-emerald-500 text-emerald-400 border-emerald-500/20",
                "On Break": "bg-amber-500 text-amber-400 border-amber-500/20",
                Offline: "bg-slate-500 text-slate-400 border-slate-500/20"
              };
              const statusClass = statusColors[staff.currentStatus] || statusColors.Working;

              return (
                <div 
                  key={sIdx} 
                  className="bg-blue-950/15 border border-blue-950/35 rounded-2xl p-4 space-y-3 relative overflow-hidden group hover:border-[#D4AF37]/30 transition-all"
                >
                  <div className="flex justify-between items-start gap-2">
                    <div>
                      <span className="text-xs font-bold text-white block leading-tight">{staff.name}</span>
                      <span className="text-[9.5px] text-slate-400 block mt-0.5">{staff.email}</span>
                    </div>
                    <span className={`text-[8.5px] font-bold uppercase px-1.5 py-0.5 rounded border ${statusClass}`}>
                      {staff.currentStatus}
                    </span>
                  </div>

                  <div className="grid grid-cols-3 gap-2 text-center py-2 bg-slate-950/15 rounded-xl border border-blue-950/25">
                    <div>
                      <span className="text-[9px] text-slate-400 block uppercase font-medium">Assigned</span>
                      <span className="text-xs font-bold font-mono text-white mt-0.5 block">{staff.assigned}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-slate-400 block uppercase font-medium">Resolved</span>
                      <span className="text-xs font-bold font-mono text-emerald-400 mt-0.5 block">{staff.completed}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-slate-400 block uppercase font-medium">Pending</span>
                      <span className="text-xs font-bold font-mono text-rose-400 mt-0.5 block">{staff.pending}</span>
                    </div>
                  </div>

                  <div className="space-y-1 text-[10px] text-slate-300">
                    <div className="flex justify-between">
                      <span>Average Resolution Speed:</span>
                      <span className="font-mono font-bold text-white">{staff.avgCompletionTime}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Billed Invoices Raised:</span>
                      <span className="font-mono font-bold text-[#D4AF37]">{staff.invoicesGenerated}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Collections Handled:</span>
                      <span className="font-mono font-bold text-emerald-400">₹{staff.collectionsHandled.toLocaleString("en-IN")}</span>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <div className="flex justify-between text-[9px] font-bold text-slate-400 uppercase">
                      <span>Productivity Efficiency</span>
                      <span className="font-mono text-[#D4AF37]">{staff.productivity}%</span>
                    </div>
                    <div className="h-1.5 w-full bg-slate-950/30 rounded-full overflow-hidden">
                      <div className="h-full bg-[#D4AF37]" style={{ width: `${staff.productivity}%` }}></div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Section: Financial Insights */}
        <div className="bg-[#1F356B] border border-blue-900/35 p-5 rounded-3xl shadow-xl">
          <div className="flex justify-between items-center border-b border-blue-950/40 pb-3 mb-4">
            <div>
              <h3 className="text-sm font-semibold tracking-wide text-[#D4AF37] uppercase flex items-center gap-1.5">
                <Bank className="w-4 h-4" />
                Financial Analytics & Cash Flow Projections
              </h3>
              <p className="text-[10px] text-slate-400">Today's direct billing operations, operational expenses, and net profit coefficients</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            {/* Box 1: Daily Revenue Activity */}
            <div className="bg-slate-950/20 p-4 rounded-2xl border border-blue-950/30 space-y-3.5">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block">Today's Cash Ledger</span>
              <div className="space-y-1.5">
                <div className="flex justify-between text-[11px] text-slate-300">
                  <span>Today's Billing:</span>
                  <span className="font-mono font-bold text-[#D4AF37]">₹{billingToday.toLocaleString("en-IN")}</span>
                </div>
                <div className="flex justify-between text-[11px] text-slate-300">
                  <span>Today's Receipts:</span>
                  <span className="font-mono font-bold text-emerald-400">₹{collectionsToday.toLocaleString("en-IN")}</span>
                </div>
                <div className="flex justify-between text-[11px] text-slate-300">
                  <span>Today's Expenses:</span>
                  <span className="font-mono font-bold text-rose-400">₹{expensesToday.toLocaleString("en-IN")}</span>
                </div>
              </div>
              <div className="border-t border-blue-950/40 pt-2 flex justify-between items-center text-[11px] font-semibold">
                <span className="text-slate-300">Net Daily Inflow:</span>
                <span className={`font-mono text-sm font-bold ${netCollectionToday >= 0 ? "text-emerald-400" : "text-rose-400"}`}>
                  ₹{netCollectionToday.toLocaleString("en-IN")}
                </span>
              </div>
            </div>

            {/* Box 2: Outstanding Aging Summary */}
            <div className="bg-slate-950/20 p-4 rounded-2xl border border-blue-950/30 space-y-3">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block">Outstanding Coefficient</span>
              <div>
                <span className="text-xs text-slate-400 block font-medium">Uncollected Billings:</span>
                <span className="text-base font-bold font-mono text-rose-400 block mt-0.5">₹{totalUnpaidInvoiced.toLocaleString("en-IN")}</span>
              </div>
              <p className="text-[10px] text-slate-400 leading-relaxed">
                Represents total billed revenues locked inside pending invoices past standard terms.
              </p>
            </div>

            {/* Box 3: Projected Monthly Cash Flows */}
            <div className="bg-slate-950/20 p-4 rounded-2xl border border-blue-950/30 space-y-3">
              <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block">Projected Cash Flows</span>
              <div className="space-y-1">
                <span className="text-xs text-slate-400 block font-medium">This Month's Overhead:</span>
                <span className="text-sm font-bold font-mono text-rose-400 block mt-0.5">₹{expensesThisMonth.toLocaleString("en-IN")}</span>
              </div>
              <p className="text-[10px] text-slate-400 leading-relaxed">
                Target collection needed to clear office overhead, software hosting, and consultant commissions.
              </p>
            </div>

          </div>
        </div>

      </div>

      {/* RIGHT: Client Insights & Compliance Grid (5 Columns) */}
      <div className="xl:col-span-5 space-y-6">
        
        {/* Section: Client Insights */}
        <div className="bg-[#1F356B] border border-blue-900/35 p-5 rounded-3xl shadow-xl">
          <div className="flex justify-between items-center border-b border-blue-950/40 pb-3 mb-4">
            <div>
              <h3 className="text-sm font-semibold tracking-wide text-[#D4AF37] uppercase flex items-center gap-1.5">
                <Users className="w-4 h-4" />
                Strategic Client Insights
              </h3>
              <p className="text-[10px] text-slate-400">Client billing segmentation, outstanding balances, and active categories</p>
            </div>
          </div>

          <div className="space-y-4">
            
            {/* Box: Highest Paying Clients */}
            <div className="space-y-2">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Top-Paying Account Groups</span>
              <div className="grid grid-cols-1 gap-1.5">
                {topPayingClients.map((c, idx) => (
                  <div key={idx} className="flex justify-between items-center bg-blue-950/15 p-2 rounded-xl border border-blue-950/30 text-[11px]">
                    <span className="truncate text-slate-300 font-medium max-w-[200px]">{c.name}</span>
                    <span className="font-mono text-emerald-400 font-bold">₹{c.amount.toLocaleString("en-IN")}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Box: Highest Outstanding */}
            <div className="space-y-2">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Highest Outstanding Balances</span>
              <div className="grid grid-cols-1 gap-1.5">
                {highestOutstandingClients.length === 0 ? (
                  <div className="text-[10px] text-slate-500 py-1 pl-2">No active outstanding balances registered!</div>
                ) : (
                  highestOutstandingClients.map((c, idx) => (
                    <div key={idx} className="flex justify-between items-center bg-blue-950/15 p-2 rounded-xl border border-blue-950/30 text-[11px]">
                      <span className="truncate text-slate-300 font-medium max-w-[200px]">{c.name}</span>
                      <span className="font-mono text-rose-400 font-bold">₹{c.amount.toLocaleString("en-IN")}</span>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Box: Recently Onboarded Clients */}
            <div className="space-y-2">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Recently Onboarded Accounts</span>
              <div className="grid grid-cols-1 gap-1.5">
                {recentlyAddedClients.map((c, idx) => (
                  <div key={idx} className="flex justify-between items-center bg-blue-950/15 p-2 rounded-xl border border-blue-950/30 text-[11px]">
                    <div className="truncate pr-2">
                      <span className="truncate text-slate-300 font-medium block">{c.name}</span>
                      <span className="text-[9px] text-slate-400 block mt-0.5">{c.category}</span>
                    </div>
                    <span className="font-mono text-slate-400 font-medium text-[9px] shrink-0">
                      {c.createdAt.substring(0, 10)}
                    </span>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </div>

        {/* Section: Compliance Insights */}
        <div className="bg-[#1F356B] border border-blue-900/35 p-5 rounded-3xl shadow-xl">
          <div className="flex justify-between items-center border-b border-blue-950/40 pb-3 mb-4">
            <div>
              <h3 className="text-sm font-semibold tracking-wide text-[#D4AF37] uppercase flex items-center gap-1.5">
                <Activity className="w-4 h-4" />
                Compliance Calendar & Filing Trackers
              </h3>
              <p className="text-[10px] text-slate-400">Tax filing frequency parameters and active compliance case volumes</p>
            </div>
          </div>

          <div className="space-y-2 h-64 overflow-y-auto pr-1">
            {complianceStats.map((stat, idx) => {
              return (
                <div 
                  key={idx} 
                  className={`flex items-center justify-between p-2.5 rounded-xl border ${stat.color} text-[11px]`}
                >
                  <div className="truncate pr-2">
                    <span className="font-bold text-white block truncate">{stat.label}</span>
                    <span className="text-[9px] text-slate-400 block mt-0.5 font-medium">Filing Terms: {stat.due}</span>
                  </div>
                  <span className="text-[10px] font-mono font-bold bg-slate-950/25 text-white px-2 py-0.5 rounded shrink-0 border border-slate-900">
                    {stat.count} Active
                  </span>
                </div>
              );
            })}
          </div>
        </div>

      </div>

    </div>
  );
}
